# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a package using Gradle and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#Publishing-using-gradle

env: # 12. 환경변수를 이름 : 값 으로 지정한다.
  S3_BUCKET_NAME: awsstudy-build # 내가 설정한 S3 버킷이름
  PROJECT_NAME: AWSstudy  # github 프로젝트 이름

name: deploy # 1. GitHub Action에서 보여질 이름

on:
  release: 
    types: [push] # 2. push시 자동으로 실행
  push:
    branches: [main] # 3. main 브랜치에서 동작
  workflow_dispatch: # 4. 수동으로 실행이 가능하다.

jobs:
  build:
    runs-on: ubuntu-latest # 5. 해당 스크립트를 작동할 OS
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout
      uses: actions/checkout@v3 # 6. 프로젝트 코드를 CheakOut한다.

    - name: Set up JDK 11
      uses: actions/setup-java@v3 #7.Github Action이 실행될 OS에 java 설치
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew # 8. gradle wrapper를 실행할 수 있도록 권한을 준다.
      shell: bash


    - name: Build with Gradle
      run: ./gradlew clean build -x test # 9. 해당 프로젝트를 build한다.
      shell: bash

    - name: Get current time
      uses: 1466587594/get-current-time@v2 # 10. 해당 기준이 UTC이기때문에 한국시간 KST로 변경
      id: current-time
      with:
        format: YYYY-MM-DDTHH-mm-ss
        utcOffset: "+09:00"

    - name: Show Current Time
      run: echo "CurrentTime=${{steps.current-time.outputs.formattedTime}}"
      # 11. 지정한 포맷대로 현재 시간을 보여준다.
    - name: Make zip file
      run: zip -r ./$PROJECT_NAME.zip . # 13. 프로젝트 이름으로 해당 폴더를 모두 압축
      shell: bash

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      # 14. aws에 해당 키값으로 접속을 진행한다.
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-2

    - name: Upload to S3
      run: aws s3 cp --region ap-northeast-2 ./$PROJECT_NAME.zip s3
      # 15. s3에 프로젝트 이름에 해당하는 폴더에 zip파일을 저장

